### ISSUE TITLE
Fortigate agent support for multicast tests

### ISSUE THREAD

**Issue by tlrichiec** [cgustave/checkitbaby#15]
A suggestion to include some support for multicast checking .

From a Fortigate perspective, a starting point could be to check the multicast session table:

`diagnose sys mcast-session list`

Or perhaps check for an IGMP join on an interface with the command:

`get router info multicast igmp groups`

From the client/server perspective, i had some success simulating multicast with the IPERF utility.

[https://gist.github.com/jayjanssen/5697813](url)

**Comment by cgustave** [comment]
ok, got it.
I think we need to implement support in lxc agent to send/receive multicast traffic based on iperf so we can trigger the traffic.
If you have some samples from your testings of short output from `diagnose sys mcast-session list` and `get router info multicast igmp groups` could you please upload them ?
Thanks,

**Comment by tlrichiec** [comment]
Output from `get router info multicast igmp groups`:

R1-H1 # get router info multicast igmp groups
IGMP Connected Group Membership
Group Address    Interface            Uptime   Expires          Last Reporter
226.94.1.1       INTERNAL-1           00:00:04 00:04:15         10.0.1.2

**Comment by cgustave** [comment]
implemented igmp group check
ex: 

FGT-B1-1:1 check [igmp_join] multicast vdom=multicast groups
FGT-B1-1:1 check [igmp_join] multicast vdom=multicast groups has group=242.0.0.1

**Comment by cgustave** [comment]
Implemented listing and sending multicast traffic with testing on the received traffic pattern.
A complete test could be like: 

# Join multicast group 239.1.1.1 from interface eth1
lxc22:1 join multicast eth1 239.1.1.1

# Listen multicast group 239.1.1.1 on port 5000
lxc22:1 listen multicast 239.1.1.1 port 5000

# Send a udp mutlicast message "hihihi" to group 239.1.1.1 from source port 10000 to destination port 5000
lxc12:1 send multicast 239.1.1.1 sport 10000 dport 5000 "hihihi"

# Check message hihihi has been seen on the receiver
lxc22:1 check [mctest] "hihihi

# Leave multicast group 239.1.1.1 from interface eth1
lxc22:1 leave multicast eth1 239.1.1.1
